version: "3.1"
services:
  notes:
    image: notes
    build: ./backend-golang/notes
    ports:
      - "6001:8080"
  note-db:
    image: postgres
    hostname: proto-db
    container_name: proto-db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "6101:5432"
